on:
  push:
    paths:
      - 'release/**.exe'
jobs:
  copy-to-release:
    name: copy release to release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/ChiikawaBest.exe
          token: ${{ secrets.ACCESS_TOKEN }}
          tag_name: ${{ github.event.head_commit.message}}
